### ISSUE TITLE
Carousel/Slideshow swipe and scroll "conflicts"

### ISSUE THREAD

**Issue by cedeber** [frontools/frontools#7]
- [ ] Block scroll while swiping on mobile
- [ ] Block swiping while scrolling on mobile

**Comment by Dalibor22x** [comment]
- [ ] Vertical scroll not working on touch devices

**Comment by Dalibor22x** [comment]
- [ ] Edge Touch Swipe doesn't work

- [ ] Edge Mouse swipe results in click

**Comment by cedeber** [comment]
Edge and Surface Touchpad are bullshit.
